import { expect, test } from "@playwright/test";
import { makeAuditSeason } from "../lib/auditFixtures";
import { createTournament } from "../lib/tournament";
import { rosterFromStar } from "../lib/players";
import type { SeasonState } from "../lib/season/types";

test("rookie role buttons combine with team filters and include academy rookies", async ({ page }) => {
  const season: SeasonState = makeAuditSeason("Role fixture");
  season.teams.forEach(team => team.players.forEach(player => { delete player.debutYear; }));
  const first = season.teams[0];
  const second = season.teams[1];
  first.players[0] = { ...first.players[0], id: "rookie-top", name: "Rookie Top", debutYear: 1 };
  second.players[1] = { ...second.players[1], id: "rookie-jungle", name: "Rookie Jungle", debutYear: 1 };
  season.franchise!.inactivePool = [{ player: { ...first.players[4], id: "rookie-support", name: "Rookie Support", debutYear: 1 }, status: "academy", inactiveYears: 1, demotedYear: 1, lastTeamId: first.id, lastTeamName: first.name }];
  await page.addInitScript(season => localStorage.setItem("draftsim-store", JSON.stringify({ version: 7, state: { season, seasonViewOpen: true } })), season);
  await page.goto("/");
  const panel = page.getByRole("region", { name: "Rookie class", exact: true });
  await panel.getByRole("button", { name: "Show rookie class" }).click();
  const rows = panel.getByTestId("rookie-row");
  const roles = panel.getByRole("group", { name: "Rookie roles" });
  await expect(rows).toHaveCount(3);
  await expect(roles.getByRole("button", { name: "Support", exact: true }).locator("img")).toHaveAttribute("src", /icon-position-utility/);
  await roles.getByRole("button", { name: "Top", exact: true }).click();
  await expect(rows).toHaveCount(1);
  await expect(rows).toContainText("Rookie Top");
  await roles.getByRole("button", { name: "Support", exact: true }).click();
  await expect(rows).toHaveCount(2);
  await panel.getByRole("button", { name: second.name, exact: true }).click();
  await expect(rows).toHaveCount(0);
  await expect(panel.getByText("No rookies match these filters")).toBeVisible();
  await roles.getByRole("button", { name: "All roles" }).click();
  await expect(rows).toHaveCount(1);
  await expect(rows).toContainText("Rookie Jungle");
  await panel.getByRole("button", { name: "All teams", exact: true }).click();
  await expect(rows).toHaveCount(3);
  await page.setViewportSize({ width: 1024, height: 768 });
  await panel.screenshot({ path: "test-results/playwright/rookie-role-filters.png" });
});

test("Swiss pairings show each team's half-star strength without opening cards", async ({ page }) => {
  const tournament = createTournament({ name: "MSI Swiss", format: "swiss", teams: Array.from({ length: 8 }, (_, index) => ({ id: `team-${index}`, name: `Swiss Team ${index + 1}`, seed: index + 1, starRating: 1, players: rosterFromStar(index === 0 ? 4.5 : 3.5) })), defaults: { format: "bo1", fearless: false, mode: "aivai", aiSide: null, aiDifficulty: "normal", timerEnabled: false } });
  await page.addInitScript(tournament => localStorage.setItem("draftsim-store", JSON.stringify({ version: 7, state: { tournament, season: null } })), tournament);
  await page.goto("/");
  const pairing = page.getByRole("group", { name: /Swiss Team 1 versus|versus Swiss Team 1$/ });
  await expect(pairing).toBeVisible();
  await expect(pairing.getByRole("img", { name: "4.5 out of 5 stars" })).toBeVisible();
  await expect(pairing.getByRole("img", { name: "3.5 out of 5 stars" })).toBeVisible();
  await page.setViewportSize({ width: 1024, height: 768 });
  const slots = pairing.locator(":scope > div").first().locator(":scope > div");
  const colors = await slots.evaluateAll(nodes => nodes.map(node => getComputedStyle(node.querySelector(".font-display")!).color));
  expect(colors[0]).toBe(colors[1]);
  const leftSlot = await slots.first().boundingBox(), rightSlot = await slots.last().boundingBox();
  const leftLogo = await slots.first().locator("svg, img").first().boundingBox();
  const rightLogo = await slots.last().locator("svg, img").first().boundingBox();
  expect(Math.abs(leftLogo!.x - leftSlot!.x)).toBeLessThan(2);
  expect(Math.abs(rightLogo!.x + rightLogo!.width - rightSlot!.x - rightSlot!.width)).toBeLessThan(2);
  const slotHeight = leftSlot!.height;
  await pairing.getByRole("button", { name: "Sim", exact: true }).click();
  await expect(pairing.getByTitle("Series winner", { exact: true })).toHaveCount(1);
  await expect(pairing.getByText("Winner", { exact: true })).toHaveCount(0);
  const winningSlot = pairing.getByTitle("Series winner", { exact: true });
  const losingSlot = pairing.getByTitle("Series loser", { exact: true });
  await expect(winningSlot.locator(".font-display")).toHaveClass(/text-emerald-300/);
  await expect(losingSlot.locator(".font-display")).toHaveClass(/text-rift-redbright/);
  await expect(winningSlot).toHaveCSS("box-shadow", "none");
  await expect(winningSlot).toHaveCSS("background-color", "rgba(0, 0, 0, 0)");
  expect((await slots.first().boundingBox())!.height).toBe(slotHeight);
  expect((await slots.last().boundingBox())!.height).toBe(slotHeight);
  await pairing.screenshot({ path: "test-results/playwright/swiss-pairing-stars.png" });
});

test("UI headings, controls and ordinary text share Inter while the wordmark uses Cinzel", async ({ page }) => {
  await page.goto("/");
  await page.evaluate(() => document.fonts.ready);
  const body = await page.locator("body").evaluate(element => getComputedStyle(element).fontFamily);
  const wordmark = page.getByRole("heading", { name: "DRAFTSIM", exact: true });
  expect(body.toLowerCase()).toContain("inter");
  expect(await wordmark.evaluate(element => getComputedStyle(element).fontFamily)).not.toBe(body);
  const controls = await page.getByRole("button").evaluateAll(elements => elements.map(element => getComputedStyle(element).fontFamily));
  expect(controls.every(font => font === body)).toBe(true);
  await page.screenshot({ path: "test-results/playwright/unified-typography-home.png" });
  await page.getByRole("button", { name: /New Season Mode/ }).click();
  await expect(page.getByRole("button", { name: "Start Season", exact: true })).toBeEnabled();
  const headings = await page.locator("h1,h2,h3").evaluateAll(elements => elements.map(element => getComputedStyle(element).fontFamily));
  expect(headings.length).toBeGreaterThan(0);
  expect(headings.every(font => font === body)).toBe(true);
  const inputs = await page.locator("input,select").evaluateAll(elements => elements.map(element => getComputedStyle(element).fontFamily));
  expect(inputs.every(font => font === body)).toBe(true);
});
