import { createSeries } from "./series";
import { validSeries } from "./importValidation";
import { makeAuditSeason } from "./auditFixtures";
import { validHistoryEntry, validRecap } from "./importValidation";
import { describe, expect, it } from "vitest";
import { createTournament, type TournamentDefaults } from "./tournament";
import { decodeTournament, encodeTournament } from "./tournamentShare";
import { TOURNAMENT_FORMATS, validateImportTree, validSeason } from "./importValidation";
const defaults: TournamentDefaults = { format: "bo1", mode: "aivai", aiDifficulty: "normal", aiSide: null, fearless: false, timerEnabled: false };
const makeTournament = (format: typeof TOURNAMENT_FORMATS[number] = "single-elim") => createTournament({
  name: "Audit tournament", format, defaults,
  teams: Array.from({length: 8}, (_, i) => ({ id: "t"+i, name: "Team "+i, seed: i+1, starRating: 3 })),
  fearlessConfig: { perSeries: false, perTeam: false, global: false },
});
describe("untrusted imports", () => {
  it.each(TOURNAMENT_FORMATS)("round trips %s including legacy teams without rosters", async (format) => {
    const original = makeTournament(format);
    const result = await decodeTournament(await encodeTournament(original));
    expect(result.error).toBeNull();
    expect(result.tournament?.format).toBe(format);
    expect(result.tournament?.teams[0].players).toHaveLength(5);
  });
  it.each([
    (t: ReturnType<typeof makeTournament>) => ({ ...t, teams: [null] }),
    (t: ReturnType<typeof makeTournament>) => ({ ...t, matches: [null] }),
    (t: ReturnType<typeof makeTournament>) => ({ ...t, matches: [{...t.matches[0], series: { games: [null] }}] }),
    (t: ReturnType<typeof makeTournament>) => ({ ...t, matches: [{...t.matches[0], blueTeamId: "missing"}] }),
    (t: ReturnType<typeof makeTournament>) => ({ ...t, teams: [t.teams[0], t.teams[0]] }),
  ])("rejects malformed data without throwing", async (corrupt) => {
    const result = await decodeTournament(JSON.stringify(corrupt(makeTournament())));
    expect(result.tournament).toBeNull();
    expect(result.error).toBeTruthy();
  });
  it("rejects seasons missing configuration and teams", () => {
    expect(validSeason({id:"s",name:"bad",tournaments:{}})).toBe(false);
  });
  it("rejects prototype keys and excessive nesting", () => {
    expect(() => validateImportTree(JSON.parse('{"__proto__":{"polluted":true}}'))).toThrow("Unsafe");
    let nested: unknown = {};
    for(let i=0;i<70;i++) nested = { nested };
    expect(() => validateImportTree(nested)).toThrow("complex");
  });
});


describe("nested payload contracts", () => {
  it("accepts a generated full season", () => {
    expect(validSeason(makeAuditSeason())).toBe(true);
  });
  it.each([
    (s: ReturnType<typeof makeAuditSeason>) => ({ ...s, teams: [{ ...s.teams[0], coach: {} }, ...s.teams.slice(1)] }),
    (s: ReturnType<typeof makeAuditSeason>) => ({ ...s, franchise: { ...s.franchise, inactivePool: [null] } }),
    (s: ReturnType<typeof makeAuditSeason>) => ({ ...s, franchise: { ...s.franchise, agencyDemands: [{}] } }),
    (s: ReturnType<typeof makeAuditSeason>) => ({ ...s, currentMeta: { ...s.currentMeta, metaOverride: { ahri: { middle: "invalid" } } } }),
  ])("rejects malformed optional season fields", corrupt => {
    expect(validSeason(corrupt(makeAuditSeason()))).toBe(false);
  });
  it("rejects the career champion null that previously crashed Hall", () => {
    expect(validHistoryEntry({ id: "test", name: "test", archivedAt: 1, complete: true,
      intlChampions: {}, splitChampions: {}, champion: null, runnerUp: null,
      playerCareers: [{ playerId: "p", champs: [null] }] })).toBe(false);
  });
  it.each([{ perPickKDA: { blue: [null], red: [] } }, { winProbTimeline: [null] }, { recapC: { wp: ["bad", 1] } }])(
    "rejects malformed replay data", fields => {
      expect(validRecap({ durationMinutes: 30, mvp: null, biggestSwing: null, ...fields })).toBe(false);
    });
});


it("rejects empty series and out-of-range draft progress while accepting a real series", () => {
  const series = createSeries({ ...defaults, timerEnabled: false, blueTeam: "Blue", redTeam: "Red" });
  expect(validSeries(series)).toBe(true);
  expect(validSeries({ ...series, games: [] })).toBe(false);
  expect(validSeries({ ...series, status: "complete" })).toBe(false);
  expect(validSeries({ ...series, games: [{ ...series.games[0], actionIndex: 999 }] })).toBe(false);
});

it("accepts a retired free agent without a previous team, as generated by franchise aging", () => {
  const season = makeAuditSeason();
  season.franchise = { ...season.franchise, inactivePool: [{ player: season.teams[0].players[0],
    status: "retired", inactiveYears: 8, demotedYear: 1, lastTeamId: "" }] };
  expect(validSeason(season)).toBe(true);
  expect(validSeason({ ...season, franchise: { ...season.franchise, inactivePool: [{ ...season.franchise.inactivePool![0], lastTeamId: null }] } })).toBe(false);
});


it("enforces node, depth, number and unsafe-key bounds with bounded traversal", () => {
  expect(() => validateImportTree({ values: [1, 2] }, 4)).not.toThrow();
  expect(() => validateImportTree({ values: [1, 2] }, 3)).toThrow("complex");
  expect(() => validateImportTree([Infinity])).toThrow("Invalid number");
  for (const key of ["__proto__", "constructor", "prototype"]) {
    expect(() => validateImportTree(JSON.parse(`{"items":[{"${key}":1}]}`))).toThrow("Unsafe");
  }
  let nested: unknown = null;
  for (let i = 0; i < 64; i++) nested = [nested];
  expect(() => validateImportTree(nested)).not.toThrow();
  expect(() => validateImportTree([nested])).toThrow("complex");
});
